import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-rural-health-clinic-cost-report-recovery",
  "engine": "recovery",
  "title": "Rural Health Clinic Cost Report Recovery",
  "shortTitle": "Rural Health Clinic Cost Report Recovery",
  "tagline": "Maximize defensible all-inclusive-rate reimbursement through visit, cost, productivity, and settlement reconciliation.",
  "industry": "Rural Provider Finance",
  "buyer": "Independent and provider-based rural health clinics",
  "uiPort": 4652,
  "apiPort": 5652,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Rural Health Clinic Cost Report Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports in one accountable workflow. Maximize defensible all-inclusive-rate reimbursement through visit, cost, productivity, and settlement reconciliation.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Rural Health Clinic Cost Report Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("clinic-status-registry","RHC01","Clinic status registry","Execute clinic status registry using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed clinic status registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Clinic status registry Reference","text","RHC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("trial-balance-ingestion","RHC02","Trial balance ingestion","Execute trial balance ingestion using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed trial balance ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Trial balance ingestion Reference","text","RHC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("visit-count-validation","RHC03","Visit count validation","Execute visit count validation using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed visit count validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Visit count validation Reference","text","RHC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("provider-fte-calculation","RHC04","Provider FTE calculation","Execute provider fte calculation using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed provider fte calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Provider FTE calculation Reference","text","RHC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("productivity-standard-analysis","RHC05","Productivity standard analysis","Execute productivity standard analysis using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed productivity standard analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Productivity standard analysis Reference","text","RHC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("allowable-cost-classification","RHC06","Allowable cost classification","Execute allowable cost classification using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed allowable cost classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Allowable cost classification Reference","text","RHC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("overhead-allocation","RHC07","Overhead allocation","Execute overhead allocation using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed overhead allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Overhead allocation Reference","text","RHC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("vaccine-cost-carve-out","RHC08","Vaccine cost carve-out","Execute vaccine cost carve-out using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed vaccine cost carve-out decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Vaccine cost carve-out Reference","text","RHC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("telehealth-treatment","RHC09","Telehealth treatment","Execute telehealth treatment using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed telehealth treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Telehealth treatment Reference","text","RHC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("bad-debt-analysis","RHC10","Bad debt analysis","Execute bad debt analysis using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed bad debt analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Bad debt analysis Reference","text","RHC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("interim-rate-reconciliation","RHC11","Interim rate reconciliation","Execute interim rate reconciliation using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed interim rate reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Interim rate reconciliation Reference","text","RHC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("air-calculation","RHC12","AIR calculation","Execute air calculation using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed air calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","AIR calculation Reference","text","RHC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("cost-report-schedule-generation","RHC13","Cost report schedule generation","Execute cost report schedule generation using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed cost report schedule generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Cost report schedule generation Reference","text","RHC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("settlement-forecast","RHC14","Settlement forecast","Execute settlement forecast using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed settlement forecast decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Settlement forecast Reference","text","RHC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]}),
feature("clinic-cost-analytics","RHC15","Clinic cost analytics","Execute clinic cost analytics using trial balances, visits, provider time, allowable costs, overhead allocations, productivity standards, vaccines, bad debt, interim payments, and cost reports.","Produce a governed clinic cost analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Clinic / Cost Reporting Period","text","Clinic / Cost Reporting Period · Standard Case"],["caseReference","Clinic cost analytics Reference","text","RHC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",631250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",763813],["domainDriver","Clinic Type","select","Independent RHC",["Independent RHC","Provider-based RHC","Provider-based exempt"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Clinic status registry case","Trial balance ingestion case","Visit count validation case","Provider FTE calculation case","Productivity standard analysis case"]})
]);
